# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d00aa763fba8d747706fef8009ae831e5ae37938d54b6e95f84543ee22a617d679a7891f7a7a8e2ec152e2c49643a80322d8c4c4255689bbcbba972fb60d1da

test:
  secret_key_base: cd0dc3b08789ee6b7224e01f2e3bafcc9a923827a1d79e45f9d12808fac58872ba9b2ca193a5aefdd7bcd3c88f152bdda721ec32ce8e9825ce3cf00e0610d321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
